const GHL_CUSTOM_FIELDS = {
    "contact.are_you_on_medicaid_or_medicare": "PrkTOch9luwDB9UG8O9e",
    "contact.attestation": "v1h5tmhxeIr4XOnfj0BV",
    "contact.authorization_date_": "gx3JmbdtEbe6uNKIdRmr",
    "contact.confirmation": "YO7qF5mJYvA4fY54MOvt",
    "contact.county": "J13n177AKjQJsbpWSNRY",
    "contact.current_insurance": "UGmuCSnaN8hvnxqALzoW",
    "contact.dependent_1_dob": "MQOfxW1BPke5HesAnvrZ",
    "contact.dependent_1_full_name": "9s4X9krX64p1BvDbEOnu",
    "contact.dependent_1_gender": "du8XJobx8KjPuoqsDF6r",
    "contact.dependent_1_phone": "Oplo8YeUlm7tvpmzZl09",
    "contact.dependent_1_relationship": "h9qBfGiK5IMjWRJ3GolN",
    "contact.dependent_1_ssn": "GIKd7yjjcGXmyUQaj8Ss",
    "contact.dependent_2_dob": "QN5M9a1FrAtl3d1Y4vHI",
    "contact.dependent_2_full_name": "1INzNYML5fFWMPTnrKUK",
    "contact.dependent_2_gender": "ZnHZEVMFyiS1k4TP4jI3",
    "contact.dependent_2_phone": "xtfqg9Uro4jGHn2172Yg",
    "contact.dependent_2_relationship": "YRINb2POouJS02CCKICS",
    "contact.dependent_2_ssn": "PKjkMEsVWNYVJJMwOH1U",
    "contact.dependent_3_dob": "X2mUcyRP1VnlFmk0xGgD",
    "contact.dependent_3_full_name": "nV418on0MWGuBKf8TBuN",
    "contact.dependent_3_gender": "Jr0mFn1RFGVj2uvMN0IL",
    "contact.dependent_3_phone": "jPGzN8mnX7o2uXD7rHuw",
    "contact.dependent_3_relationship": "Gbfd7ARklUtCqUSsiSq5",
    "contact.dependent_3_ssn": "t31l4xTNm03yQJTEZ4W9",
    "contact.dependent_4_dob": "69pWqEDQ0LzH5ZtidbvI",
    "contact.dependent_4_full_name": "QBBZLZ3cEltwSo2GTFV1",
    "contact.dependent_4_gender": "SHmTN9udEgvRwlYXhbgL",
    "contact.dependent_4_phone": "RNK6qseHFPec0ue01UOD",
    "contact.dependent_4_relationship": "uIbwtFEY2bRRRbsIg3jD",
    "contact.dependent_4_ssn": "XR8YWhKIvZulLrf8ziwF",
    "contact.do_you_have_a_2nd_dependent": "SMBEk7yVtVbfQpfP6SFF",
    "contact.do_you_have_a_3rd_dependent": "4v8z5EnfvxMjNMCtDyJZ",
    "contact.do_you_have_tax_dependants": "l9PG6xIzWjPrZsdjZYhY",
    "contact.do_you_want_to_enroll_dependents": "pte3uE2EmfsmLuxISI6j",
    "contact.do_you_want_to_enroll_spouse": "650AA4GB3JX5PpDT5bdg",
    "contact.do_your_partner_uses_tobacco": "18AKbHPSGdKGM96z65d9",
    "contact.estimated_2024_household_annual_income": "hMKwTHsd47sUQC8m3Lyp",
    "contact.estimated_household_annual_income": "1MmQENwjWciCMoyncUgT",
    "contact.name_of_employer": "salAUoQKzhR948aYoTyP",
    "contact.primary_ssn": "xUbgCi4UfLJeUlfhe5pX",
    "contact.sign": "8CbNoMTqjEPDxjw7HlaI",
    "contact.spouse_date_of_birth": "a8AYDswgrTsQ2O9icKrd",
    "contact.spouse_full_name": "ccilFUUGkZJ7oF49lsXF",
    "contact.spouse_legal_last_name": "fG3vJCAAZBY9FVGKsv4f",
    "contact.spouse_ssn": "jVMcfdrTA3XMBfYqd1JF",
    "contact.signature": "KgWxAz6E3n0XP9KFfrA3",
    "contact.tobacco_user": "5ANPoKcSaXiVrt4Ntykx",
    "contact.us_national": "W4F05fm1dP5NQUFTHyRg"
}


export default GHL_CUSTOM_FIELDS